---
 - name: Create VM from template
   vmware_guest:
    hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: false
    name: "{{ name }}"
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    folder: "{{ folder }}"
    state: poweredon
    template: "{{ template }}"
    disk:
    - size_gb: 16
      type: thin
      autoselect_datastore: true
    networks:
    - name: "{{ portgroup }}"
      ip: "{{ server_ip }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway }}"
      dns_servers: "{{ dns_ip }}"
      type: static
       
 - name: "Wait for VM Tools"
   local_action:
    module: vmware_guest_tools_wait
    hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: false
    name: "{{ name }}"

 - name: "Wait for SSH"
   local_action:
    module: wait_for
    host: "{{ server_ip }}"
    port: 22
    state: started
    timeout: 60

 - name: "Add Provioned VM to Host Group"
   add_host:
    hostname: "{{ server_ip }}"
    groups: webservers
